# Generated by Django 5.2.6 on 2025-09-21 18:32

import django.db.models.deletion
import olympiads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='Olympiad Field Name')),
                ('schedule', models.TextField(max_length=200, verbose_name='Olympiad Field Schedule')),
                ('type', models.CharField(choices=[('KSM', 'KSM'), ('OSN', 'OSN')], max_length=50, verbose_name='Olympiad Type')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Ketik yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu). Untuk menghapusnya, klik nama yang ingin dihapus hingga berwarna biru/terang, lalu tekan delete atau backspace.', to='students.student', verbose_name="Olympiad's Students")),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name="Olympiad's Teacher")),
            ],
            options={
                'verbose_name': 'Olympiad Field',
                'verbose_name_plural': 'Olympiad Fields',
                'db_table': 'olympiad_fields',
                'ordering': ['type', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Report Date')),
                ('report_photo', models.ImageField(default='no-image.png', help_text='Format foto harus .jpg atau .jpeg', upload_to=olympiads.models.PathAndRename('olimpiade'), verbose_name='Report Photo')),
                ('notes', models.TextField(blank=True, max_length=200, verbose_name='Olympiad Notes')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiadfield', verbose_name='Olympiad Field')),
                ('students', models.ManyToManyField(blank=True, help_text='Ketik yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu)', to='students.student', verbose_name="Student's Students")),
            ],
            options={
                'verbose_name': 'Olympiad Report',
                'verbose_name_plural': 'Olympiad Reports',
                'db_table': 'olympiad_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddIndex(
            model_name='olympiadfield',
            index=models.Index(fields=['id', 'slug'], name='olympiad_fi_id_cce7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadreport',
            index=models.Index(fields=['id'], name='olympiad_re_id_657982_idx'),
        ),
    ]
