# Generated by Django 5.2.6 on 2025-09-21 18:32

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('nisn', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=10)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('student_birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('student_birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('student_status', models.CharField(blank=True, default='Aktif', max_length=20)),
                ('photo', models.ImageField(blank=True, default='blank-profile.png', help_text='Format foto .jpg/.jpeg', null=True, upload_to=students.models.PathAndRename('student'))),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class', verbose_name='Kelas')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['student_class__class_name', 'student_name'],
                'indexes': [models.Index(fields=['nis', 'id'], name='students_nis_abcc3e_idx')],
            },
        ),
    ]
