# Generated by Django 5.2.6 on 2025-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=255, null=True, verbose_name='NIS')),
                ('nisn', models.CharField(blank=True, max_length=255, null=True, verbose_name='NISN')),
                ('name', models.CharField(help_text='Dilengkapi gelar jika ada', max_length=255, verbose_name='Nama Lengkap')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Angkatan')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tempat Lahir')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1, null=True, verbose_name='Jenis Kelamin (L/P)')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alamat')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi')),
                ('state', models.CharField(blank=True, default='Indonesia', max_length=100, null=True, verbose_name='Negara')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp')),
                ('last_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kelas Terakhir')),
                ('graduate_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Tahun Lulus')),
                ('undergraduate_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jurusan Sarjana (S1)')),
                ('undergraduate_university', models.CharField(blank=True, max_length=255, null=True, verbose_name='Universitas Sarjana (S1)')),
                ('undergraduate_university_entrance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jalur Masuk Sarjana (S1)')),
                ('postgraduate_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jurusan Magister (S2)')),
                ('postgraduate_university', models.CharField(blank=True, max_length=255, null=True, verbose_name='Universitas Magister (S2)')),
                ('postgraduate_university_entrance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jalur Masuk Magister (S2)')),
                ('doctoral_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jurusan Doktoral (S3)')),
                ('doctoral_university', models.CharField(blank=True, max_length=255, null=True, verbose_name='Universitas Doktoral (S3)')),
                ('doctoral_university_entrance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jalur Masuk Doktoral (S3)')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pekerjaan')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Perusahaan')),
                ('married', models.CharField(blank=True, choices=[('Ya', 'Sudah'), ('Tidak', 'Belum')], default='Tidak', max_length=20, null=True, verbose_name='Status Pernikahan')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Ayah')),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Ibu')),
                ('family_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telpon Orang Tua')),
                ('photo', models.ImageField(blank=True, default='blank-profile.png', null=True, upload_to='alumni', verbose_name='Foto Alumni')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'db_table': 'alumni',
                'ordering': ['-group', 'name'],
                'indexes': [models.Index(fields=['id', 'name'], name='alumni_id_a51d3c_idx')],
            },
        ),
    ]
