services:
  backend:
    build: .
    container_name: smait-backend
    command: gunicorn smaitalbinaa_backend.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --timeout 120
    volumes:
      - .:/app
      - staticfiles_volume:/app/staticfiles
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: smait-db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${LOCAL_MYSQL_DB_NAME}
      MYSQL_USER: ${LOCAL_MYSQL_DB_USER}
      MYSQL_PASSWORD: ${LOCAL_MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${LOCAL_MYSQL_ROOT_PASSWORD} # Add this to your .env
    ports:
      - "3307:3306" # Expose on 3307 to avoid conflict with local MySQL on 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
  static_volume:
  staticfiles_volume:
  media_volume: