# Generated by Django 5.2.6 on 2025-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Jika tidak diisi, akan otomatis terisi dengan judul', max_length=255, unique_for_date='created_at'),
        ),
    ]
