# Generated by Django 5.2.6 on 2025-10-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_post_tags'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_post_id_015fcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_active_33cf79_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_slug_2cc621_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_status_def373_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_author__d284fa_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='Pada PC, Tekan Ctrl untuk memilih lebih dari satu kategori', related_name='posts', to='news.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Jika tidak diisi, akan otomatis terisi dengan judul', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at', 'author'], name='comments_post_id_f8e04a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug', 'created_at', 'author'], name='posts_slug_8858ea_idx'),
        ),
    ]
