# Generated by Django 5.2.6 on 2025-10-01 17:15

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_comment_comments_post_id_015fcc_idx_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
