# Generated by Django 5.2.6 on 2025-09-21 18:32

import achievements.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('type', models.CharField(max_length=100, verbose_name='Jenis Lomba')),
                ('level', models.CharField(max_length=100, verbose_name='Tingkat Lomba')),
                ('year', models.CharField(max_length=4, verbose_name='Tahun Lomba')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Lomba')),
                ('organizer', models.CharField(max_length=100, verbose_name='Penyelenggara Lomba')),
                ('awardee', models.CharField(max_length=255, verbose_name='Peraih Pemenang')),
                ('awardee_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kelas Pemenang')),
                ('school', models.CharField(default='SMAS IT Al Binaa', max_length=100, verbose_name='Sekolah')),
                ('field', models.CharField(max_length=100, verbose_name='Bidang Lomba')),
                ('predicate', models.CharField(max_length=100, verbose_name='Predikat')),
                ('certificate', models.FileField(blank=True, null=True, upload_to=achievements.models.PathAndRename('prestasi/sertifikat'), verbose_name='Serfifikat')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=achievements.models.PathAndRename('prestasi'), verbose_name='Foto')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2024/2025', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Ketik yang ingin dicari dan pilih.', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Pemenang')),
            ],
            options={
                'verbose_name': 'Prestasi',
                'verbose_name_plural': 'Prestasi',
                'db_table': 'prestasi',
                'ordering': ['-created_at', '-year', 'name', 'awardee'],
                'indexes': [models.Index(fields=['id'], name='prestasi_id_242418_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramPrestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_prestasi', models.CharField(max_length=200, verbose_name='Program Prestasi')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('pencapaian', models.CharField(max_length=200, verbose_name='Pencapaian')),
                ('catatan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Catatan')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_peserta', models.ManyToManyField(help_text='Ketik yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu)', to='students.student', verbose_name='Santri')),
            ],
            options={
                'verbose_name': 'Program Prestasi',
                'verbose_name_plural': 'Program Prestasi',
                'db_table': 'program_prestasi',
                'ordering': ['-tanggal', 'program_prestasi'],
                'indexes': [models.Index(fields=['id'], name='program_pre_id_da91d1_idx')],
            },
        ),
    ]
