# Generated by Django 5.2.8 on 2026-01-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='semester',
            field=models.CharField(default='Genap', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='programprestasi',
            name='semester',
            field=models.CharField(default='Genap', max_length=7, null=True),
        ),
    ]
