# Generated by Django 5.2.6 on 2025-09-21 18:32

import extracurriculars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Extracurricular/SC Name')),
                ('short_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Name')),
                ('schedule', models.CharField(choices=[(None, 'Choose training Day'), ('Senin', 'Monday'), ('Selasa', 'Tuesday'), ('Rabu', 'Wednesday'), ('Kamis', 'Thursday'), ('Jumat', 'Friday'), ('Sabtu', 'Saturday'), ('Ahad', 'Sunday')], max_length=15, null=True, verbose_name='Schedule')),
                ('time', models.CharField(choices=[(None, 'Choose training time'), ('Pagi', 'Morning'), ('Siang', 'Noon'), ('Sore', 'Evening'), ('Malam', 'Night')], max_length=15, null=True, verbose_name='Time')),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='no-image.png', help_text='format logo .jpg/.jpeg', null=True, upload_to=extracurriculars.models.PathAndRename('ekskul/logo'))),
                ('type', models.CharField(blank=True, choices=[(None, 'Select Type'), ('Ekskul', 'Ekstrakurikuler'), ('SC', 'Study Club')], max_length=20, verbose_name='Type')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('status', models.CharField(default='Aktif', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Pada PC, Tekan Ctrl + Clik nama santri untuk memilih lebih dari satu. <br> Pada HP, Beri ceklis (✅) untuk menambahkan atau unchecklist untuk menghapusnya.', to='students.student', verbose_name='Members')),
                ('teacher', models.ManyToManyField(help_text='Ketik nama yang ingin dicari dan pilih pembimbing. Kamu bisa memilih lebih dari 1 (satu). Untuk menghapusnya, klik nama yang ingin dihapus hingga berwarna biru/terang, lalu tekan delete atau backspace.', to='teachers.teacher', verbose_name='Teachers')),
            ],
            options={
                'verbose_name': 'Extracurricular',
                'verbose_name_plural': 'Extracurriculars',
                'db_table': 'extracurriculars',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='extracurric_id_fe79dc_idx')],
            },
        ),
    ]
