# Generated by Django 5.2.6 on 2025-09-21 18:32

import django.db.models.deletion
import extracurricular_reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extracurriculars', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Report Date')),
                ('report_notes', models.TextField(blank=True, max_length=200, verbose_name='Notes')),
                ('photo', models.ImageField(default='no-image.png', help_text='Image must be .jpg/.jpeg/.png format', upload_to=extracurricular_reports.models.PathAndRename('ekskul/laporan'))),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracurriculars.extracurricular')),
                ('students', models.ManyToManyField(help_text='Ketik nama yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu). Untuk menghapusnya, klik nama yang ingin dihapus hingga berwarna biru/terang, lalu tekan delete atau backspace.', to='students.student')),
                ('teacher', models.ManyToManyField(help_text='Ketik nama yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu). Untuk menghapusnya, klik nama yang ingin dihapus hingga berwarna biru/terang, lalu tekan delete atau backspace.', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'extracurricular_reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['id', 'report_date'], name='extracurric_id_810794_idx')],
            },
        ),
    ]
