# Generated by Django 5.2.6 on 2025-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Nama Event')),
                ('event_start_date', models.DateField(verbose_name='Tanggal Mulai Event')),
                ('event_end_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Berakhir Event')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Deskripsi')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori')),
                ('type', models.CharField(choices=[(None, '----Pilih Kategori Gender----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Tipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Calendar',
                'verbose_name_plural': 'Academic Calendars',
                'db_table': 'academic_calendar',
                'ordering': ['event_name'],
                'indexes': [models.Index(fields=['id', 'event_name', 'event_start_date'], name='academic_ca_id_8ca4d7_idx')],
            },
        ),
    ]
