# Generated by Django 5.2.6 on 2025-09-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelompok', models.CharField(max_length=255, verbose_name='Nama Kelompok')),
                ('jenis_kelompok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jenis Kelompok')),
                ('jadwal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jadwal')),
                ('waktu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Waktu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('santri', models.ManyToManyField(blank=True, help_text='Ketik nama yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu). Untuk menghapusnya, klik nama yang ingin dihapus hingga berwarna biru/terang, lalu tekan delete atau backspace.', to='students.student', verbose_name='Santri')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['nama_kelompok', 'pelajaran'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=100, verbose_name='Mata Pelajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pembimbing', models.ManyToManyField(blank=True, to='teachers.teacher', verbose_name='Pembimbing')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['nama_pelajaran'],
            },
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bimbingan', models.DateField(verbose_name='Tanggal')),
                ('waktu_bimbingan', models.TimeField(verbose_name='Waktu')),
                ('catatan_bimbingan', models.TextField(blank=True, max_length=200, verbose_name='Catatan')),
                ('foto', models.ImageField(default='no-image.png', help_text='Format foto .jpg atau .jpeg', upload_to='privat/laporan', verbose_name='Bukti Foto')),
                ('semester', models.CharField(blank=True, default='Ganjil', max_length=50, null=True, verbose_name='Semester')),
                ('tahun_ajaran', models.CharField(blank=True, default='2025/2026', max_length=50, null=True, verbose_name='Tahun Ajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kehadiran_santri', models.ManyToManyField(help_text='Pada PC, tekan CTRL + Clik untuk memilih lebih dari satu (1).', to='students.student', verbose_name='Kehadiran Peserta')),
                ('kelompok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='private.group')),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Pembimbing')),
                ('pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.subject', verbose_name='Pelajaran')),
            ],
            options={
                'verbose_name': 'Private',
                'verbose_name_plural': 'Private',
                'db_table': 'private',
                'ordering': ['-tanggal_bimbingan'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.subject', verbose_name='Pelajaran'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['id', 'nama_pelajaran'], name='subjects_id_42f7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='private',
            index=models.Index(fields=['id', 'tanggal_bimbingan'], name='private_id_e01088_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['id'], name='groups_id_f54bab_idx'),
        ),
    ]
