# Generated by Django 5.2.6 on 2025-09-21 18:32

import django.db.models.deletion
import teachers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niy', models.IntegerField(default=0, verbose_name='NIY')),
                ('teacher_name', models.CharField(help_text='Nama lengkap pembina, misal: Aam Hamdani, S.Pd.', max_length=100, verbose_name='Nama Pembina')),
                ('short_name', models.CharField(blank=True, help_text='Nama singkat pembina, misal: Aam Hamdani, S.Pd. menjadi Aam', max_length=100, null=True, verbose_name='Nama Singkat')),
                ('gender', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('address', models.CharField(blank=True, help_text='Alamat lengkap pembina, misal: Jl. Raya No. 123, Jakarta', max_length=100, null=True)),
                ('job', models.CharField(blank=True, help_text='Pekerjaan pembina, misal: Guru Matematika, Kepala Sekolah, dll', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='smaitalbinaa.ekskul@outlook.com', max_length=254)),
                ('phone', models.CharField(blank=True, default=0, help_text='Nomor telepon pembina, misal: 08123456789', max_length=20)),
                ('photo', models.ImageField(blank=True, default='blank-profile.png', help_text='format foto .jpg/.jpeg', null=True, upload_to=teachers.models.PathAndRename('user'))),
                ('work_area', models.CharField(blank=True, help_text='Wilayah Kerja guru ini', max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='Aktif', help_text='Status aktif atau tidaknya guru ini', max_length=20, null=True)),
                ('day_off', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], default='Sabtu', help_text="The teacher's designated day off.", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['teacher_name'],
                'indexes': [models.Index(fields=['id', 'niy'], name='teachers_id_a1a279_idx')],
            },
        ),
    ]
