# Generated by Django 5.2.6 on 2025-09-21 18:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('nomor_surat', models.PositiveBigIntegerField(verbose_name='No Surat')),
                ('nama_surat', models.CharField(max_length=255, verbose_name='Nama Surat')),
                ('ayat', models.PositiveBigIntegerField(verbose_name='Ayat')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('semester', models.CharField(default='Ganjil', max_length=7)),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Target',
                'db_table': 'tilawah_target',
                'ordering': ['tanggal'],
                'indexes': [models.Index(fields=['id'], name='tilawah_tar_id_f0168f_idx')],
                'unique_together': {('tanggal', 'nomor_surat', 'ayat'), ('tanggal', 'nomor_surat', 'ayat', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Tahfidz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembimbing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pembimbing')),
                ('hafalan', models.CharField(max_length=255, verbose_name='Juz yang dihafal')),
                ('pencapaian_sebelumnya', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pencapaian Sebelumnya')),
                ('pencapaian_sekarang', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pencapaian Sekarang')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Santri')),
            ],
            options={
                'verbose_name': 'Tahfidz',
                'verbose_name_plural': 'Tahfidz',
                'db_table': 'tahfidz',
                'ordering': ['-santri'],
                'indexes': [models.Index(fields=['id'], name='tahfidz_id_f6bad8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tilawah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.now, verbose_name='Tanggal')),
                ('kehadiran', models.CharField(blank=True, choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Telat', 'Telat'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], default='Hadir', max_length=10, null=True, verbose_name='Kehadiran')),
                ('tercapai', models.BooleanField(blank=True, choices=[(True, 'True'), (False, 'False')], default=True, max_length=10, null=True, verbose_name='Tercapai?')),
                ('target', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Target Tilawah Hari Ini')),
                ('halaman', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Halaman')),
                ('surat', models.PositiveBigIntegerField(blank=True, choices=[(1, 'Al-Fatihah'), (2, 'Al-Baqarah'), (3, "Ali 'Imran"), (4, "An-Nisa'"), (5, "Al-Ma'idah"), (6, "Al-An'am"), (7, "Al-A'raf"), (8, 'Al-Anfal'), (9, 'At-Tawbah'), (10, 'Yunus'), (11, 'Hud'), (12, 'Yusuf'), (13, "Ar-Ra'd"), (14, 'Ibrahim'), (15, 'Al-Hijr'), (16, 'An-Nahl'), (17, "Al-Isra'"), (18, 'Al-Kahf'), (19, 'Maryam'), (20, 'Ta Ha'), (21, "Al-Anbiya'"), (22, 'Al-Hajj'), (23, "Al-Mu'minun"), (24, 'An-Nur'), (25, 'Al-Furqan'), (26, "Ash-Shu'ara'"), (27, 'An-Naml'), (28, 'Al-Qasas'), (29, 'Al-Ankabut'), (30, 'Ar-Rum'), (31, 'Luqman'), (32, 'As-Sajdah'), (33, 'Al-Ahzab'), (34, "Saba'"), (35, 'Fatir'), (36, 'Ya Sin'), (37, 'As-Saffat'), (38, 'Sad'), (39, 'Az-Zumar'), (40, 'Ghafir'), (41, 'Fussilat'), (42, 'Ash-Shura'), (43, 'Az-Zukhruf'), (44, 'Ad-Dukhan'), (45, 'Al-Jathiyah'), (46, 'Al-Ahqaf'), (47, 'Muhammad'), (48, 'Al-Fath'), (49, 'Al-Hujurat'), (50, 'Qaf'), (51, 'Adh-Dhariyat'), (52, 'At-Tur'), (53, 'An-Najm'), (54, 'Al-Qamar'), (55, 'Ar-Rahman'), (56, "Al-Waqi'ah"), (57, 'Al-Hadid'), (58, 'Al-Mujadila'), (59, 'Al-Hashr'), (60, 'Al-Mumtahanah'), (61, 'As-Saff'), (62, "Al-Jumu'ah"), (63, 'Al-Munafiqun'), (64, 'At-Taghabun'), (65, 'At-Talaq'), (66, 'At-Tahrim'), (67, 'Al-Mulk'), (68, 'Al-Qalam'), (69, 'Al-Haqqah'), (70, "Al-Ma'arij"), (71, 'Nuh'), (72, 'Al-Jinn'), (73, 'Al-Muzzammil'), (74, 'Al-Muddaththir'), (75, 'Al-Qiyamah'), (76, 'Al-Insan'), (77, 'Al-Mursalat'), (78, "An-Naba'"), (79, "An-Nazi'at"), (80, 'Abasa'), (81, 'At-Takwir'), (82, 'Al-Infitar'), (83, 'Al-Mutaffifin'), (84, 'Al-Inshiqaq'), (85, 'Al-Buruj'), (86, 'At-Tariq'), (87, "Al-A'la"), (88, 'Al-Ghashiyah'), (89, 'Al-Fajr'), (90, 'Al-Balad'), (91, 'Ash-Shams'), (92, 'Al-Lail'), (93, 'Ad-Duhaa'), (94, 'Ash-Sharh'), (95, 'At-Tin'), (96, "Al-'Alaq"), (97, 'Al-Qadr'), (98, 'Al-Bayyinah'), (99, 'Az-Zalzalah'), (100, "Al-'Adiyat"), (101, "Al-Qari'ah"), (102, 'At-Takathur'), (103, 'Al-Asr'), (104, 'Al-Humazah'), (105, 'Al-Fil'), (106, 'Quraysh'), (107, "Al-Ma'un"), (108, 'Al-Kawthar'), (109, 'Al-Kafirun'), (110, 'An-Nasr'), (111, 'Al-Masad'), (112, 'Al-Ikhlas'), (113, 'Al-Falaq'), (114, 'An-Nas')], null=True, verbose_name='Surat Terakhir')),
                ('ayat', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Ayat Terakhir')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('tajwid', models.CharField(blank=True, choices=[(None, '----Pilih Nilai Tahsin----'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ("Da'if", "Da'if")], max_length=255, null=True, verbose_name='Tajwid')),
                ('kelancaran', models.CharField(blank=True, choices=[(None, '----Pilih Nilai Tahsin----'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ("Da'if", "Da'if")], max_length=255, null=True, verbose_name='Kelancaran')),
                ('semester', models.CharField(default='Ganjil', max_length=7)),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pendamping', models.ManyToManyField(blank=True, max_length=255, related_name='Pendamping', to='teachers.teacher')),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Santri')),
                ('target_tilawah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tahfidz.target', verbose_name='Target')),
            ],
            options={
                'verbose_name': 'Tilawah',
                'verbose_name_plural': 'Tilawah',
                'db_table': 'tilawah',
                'ordering': ['-tanggal', 'santri'],
                'indexes': [models.Index(fields=['id'], name='tilawah_id_ea79ec_idx')],
                'unique_together': {('tanggal', 'santri'), ('tanggal', 'santri', 'semester', 'academic_year')},
            },
        ),
    ]
