# Generated by Django 5.2.8 on 2026-01-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0002_alter_tahfidz_pembimbing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahfidz',
            name='semester',
            field=models.CharField(default='Genap', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='semester',
            field=models.CharField(default='Genap', max_length=7),
        ),
        migrations.AlterField(
            model_name='tilawah',
            name='semester',
            field=models.CharField(default='Genap', max_length=7),
        ),
    ]
