# Generated by Django 5.2.8 on 2026-02-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahfidz', '0003_alter_tahfidz_semester_alter_target_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='halaman',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Halaman'),
        ),
    ]
