# Generated by Django 5.2.6 on 2025-09-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Pelajaran')),
                ('short_name', models.CharField(default='', max_length=30, verbose_name='Nama Singkat')),
                ('category', models.CharField(choices=[(None, '----Pilih Kategori----'), ("Syar'i", "Syar'i"), ('Ashri', 'Ashri'), ('Netral', 'Netral')], default="Syar'i", max_length=20, verbose_name='Kategori')),
                ('type', models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putra', 'Putri'), ('Putra-Putri', 'Putra & Putri')], default='Putra', max_length=20, verbose_name='Tipe')),
                ('status', models.CharField(default='Aktif', max_length=50, verbose_name='Status Pelajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Subject',
                'verbose_name_plural': 'Course Subjects',
                'db_table': 'subject',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'name'], name='subject_id_c229ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=20, verbose_name='Kode Pelajaran')),
                ('type', models.CharField(choices=[(None, '----Pilih Kategori Kelas----'), ('Putra', 'Putra'), ('Putra', 'Putri'), ('Putra-Putri', 'Putra & Putri')], default='Putra', max_length=20, verbose_name='Tipe')),
                ('periods_per_week', models.PositiveIntegerField(default=1, help_text='Number of periods this lesson occurs per week (1-4).')),
                ('consecutive_periods_needed', models.PositiveIntegerField(default=1, help_text='Number of consecutive periods for one session (e.g., 2 for a double period).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='classes.class', verbose_name='Kelas')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.teacher', verbose_name='Guru')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.subject', verbose_name='Mata Pelajaran')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['course'],
                'indexes': [models.Index(fields=['id', 'course'], name='courses_id_07ef52_idx')],
            },
        ),
    ]
