# Generated by Django 5.2.6 on 2025-10-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_test', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='blogtest',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='blog_test.caterogytest'),
        ),
    ]
