# Generated by Django 5.2.8 on 2026-01-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_test', '0003_blogtest_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtest',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog_test.caterogytest'),
        ),
    ]
