# Generated by Django 5.2.6 on 2025-09-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extracurriculars', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[(None, '----Pilih Nilai----'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=3)),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracurricular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extracurriculars.extracurricular')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'scores',
                'ordering': ['student', 'extracurricular'],
                'indexes': [models.Index(fields=['id'], name='scores_id_ab828f_idx')],
            },
        ),
    ]
