# Generated by Django 5.2.6 on 2025-09-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_members', models.TextField(blank=True, null=True, verbose_name='Anggota Sebelumnya')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=50, verbose_name='Status Tim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(help_text='Ketik yang ingin dicari dan pilih. Kamu bisa memilih lebih dari 1 (satu). Untuk menghapusnya, klik nama yang ingin dihapus hingga berwarna biru/terang, lalu tekan delete atau backspace.', related_name='teams', to='students.student', verbose_name='Anggota Tim')),
                ('team_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leaders', to='students.student', verbose_name='Ketua Tim')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Nama Project')),
                ('start_date', models.DateField(max_length=255, verbose_name='Tanggal Mulai Project')),
                ('end_date', models.DateField(max_length=255, verbose_name='Tanggal Akhir Project')),
                ('description', models.TextField(max_length=2000, verbose_name='Deskripsi Project')),
                ('step_to_achieve', models.TextField(max_length=2000, verbose_name='Langkah Mencapai Project')),
                ('task_organizing', models.TextField(max_length=2000, verbose_name='Pembagian Tugas Project')),
                ('slug', models.SlugField(max_length=255)),
                ('semester', models.CharField(max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2024/2025', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Pembimbing')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_projects.team')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'student_projects',
                'ordering': ['-start_date', 'project_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=255, verbose_name='Tanggal')),
                ('to_do_list', models.TextField(max_length=2000, verbose_name='List Pekerjaan Hari Ini')),
                ('target_today', models.TextField(max_length=2000, verbose_name='Target Hari ini')),
                ('problems', models.TextField(max_length=2000, verbose_name='Kendala yang dihadapi')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_projects.project', verbose_name='Nama Proyek')),
            ],
            options={
                'verbose_name': 'Daily Plan',
                'verbose_name_plural': 'Daily Plans',
                'db_table': 'daily_plans',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['id'], name='daily_plans_id_2fdbd5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['id'], name='teams_id_2236c1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id', 'slug'], name='student_pro_id_e14d7c_idx'),
        ),
    ]
