# Generated by Django 5.2.6 on 2025-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanPertanggungJawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=255, verbose_name='Nama Program')),
                ('tujuan', models.TextField(max_length=1000, verbose_name='Tujuan Program')),
                ('indikator', models.TextField(max_length=1000, verbose_name='Indikator Keberhasilan')),
                ('waktu_pelaksanaan', models.CharField(max_length=255, verbose_name='Waktu Pelaksanaan')),
                ('status', models.CharField(max_length=255, verbose_name='Status Pelaksanaan')),
                ('capaian', models.TextField(max_length=1000, verbose_name='Capaian Program')),
                ('keterangan', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Keterangan')),
                ('penanggungjawab', models.CharField(blank=True, max_length=255, null=True, verbose_name='Penanggung Jawab')),
                ('pengeluaran', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pengeluaran')),
                ('tahun_ajaran', models.CharField(default='2025/2026', max_length=40, verbose_name='Tahun Ajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LPJ',
                'verbose_name_plural': 'LPJ',
                'db_table': 'lpj',
                'ordering': ['program'],
                'indexes': [models.Index(fields=['id', 'program'], name='lpj_id_187387_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=255, verbose_name='Nama Program')),
                ('tujuan', models.TextField(max_length=1000, verbose_name='Tujuan Program')),
                ('indikator', models.TextField(max_length=1000, verbose_name='Indikator Keberhasilan')),
                ('waktu_pelaksanaan', models.CharField(max_length=255, verbose_name='Waktu Pelaksanaan')),
                ('keterangan', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Keterangan')),
                ('penanggungjawab', models.CharField(blank=True, max_length=255, null=True, verbose_name='Penanggung Jawab')),
                ('anggaran', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anggaran')),
                ('tahun_ajaran', models.CharField(default='2025/2026', max_length=40, verbose_name='Tahun Ajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proker',
                'verbose_name_plural': 'Proker',
                'db_table': 'proker',
                'ordering': ['program'],
                'indexes': [models.Index(fields=['id', 'program'], name='proker_id_fe8691_idx')],
            },
        ),
    ]
