# Generated by Django 5.2.6 on 2025-09-21 18:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('time_start', models.TimeField()),
                ('short_time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('short_time_end', models.TimeField()),
                ('type', models.CharField(choices=[(None, '----Pilih Kategori Gender----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Tipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'periods',
                'ordering': ['number', 'type'],
                'indexes': [models.Index(fields=['id', 'number'], name='periods_id_caf3d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReporterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_day', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=10, verbose_name='Hari')),
                ('schedule_time', models.CharField(choices=[('1', 'Jam ke-1'), ('2', 'Jam ke-2'), ('3', 'Jam ke-3'), ('4', 'Jam ke-4'), ('5', 'Jam ke-5'), ('6', 'Jam ke-6'), ('7', 'Jam ke-7'), ('8', 'Jam ke-8'), ('9', 'Jam ke-9')], max_length=20, verbose_name='Jam Ke-')),
                ('time_start', models.TimeField(default=datetime.time(7, 0), verbose_name='Waktu Mulai')),
                ('time_end', models.TimeField(default=datetime.time(7, 0), verbose_name='Waktu Akhir')),
                ('semester', models.CharField(default='Ganjil', max_length=7, null=True)),
                ('academic_year', models.CharField(blank=True, default='2025/2026', max_length=20, null=True)),
                ('type', models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri')], default='putra', max_length=20, verbose_name='Tipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Tim Piket')),
            ],
            options={
                'verbose_name': 'Reporter Schedule',
                'verbose_name_plural': 'Reporter Schedules',
                'db_table': 'reporter_schedules',
                'ordering': ['-schedule_day', 'schedule_time'],
                'indexes': [models.Index(fields=['schedule_day', 'schedule_time'], name='reporter_sc_schedul_449fa5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_day', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=10, verbose_name='Hari')),
                ('semester', models.CharField(default='Ganjil', max_length=7)),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('type', models.CharField(choices=[(None, '----Pilih Kategori Gender----'), ('Putra', 'Putra'), ('Putri', 'Putri')], default='Putra', max_length=20, verbose_name='Tipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='classes.class', verbose_name='Kelas')),
                ('schedule_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='courses.course', verbose_name='Pelajaran')),
                ('schedule_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedules.period', verbose_name='Jam ke-')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'ordering': ['-schedule_day', 'schedule_class', 'schedule_time'],
                'indexes': [models.Index(fields=['schedule_day', 'schedule_time'], name='schedules_schedul_6b3f5c_idx')],
                'unique_together': {('schedule_day', 'schedule_time', 'schedule_class', 'type', 'semester', 'academic_year'), ('schedule_day', 'schedule_time', 'teacher')},
            },
        ),
    ]
